# Site settings
title: Venam's Blog
email: x7e1@psychology.wtf
description: > # this means to ignore newlines until "baseurl:"
  A deliberate person's ideas and concepts
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://venam.nixers.net" # the base hostname & protocol for your site
github_username:  venam

markdown: kramdown

plugins:
        - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge
