# Site settings
title: Venam's Blog
email: patrick@iotek.org
description: > # this means to ignore newlines until "baseurl:"
  A deliberate person's ideas and concepts
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://venam.nixers.net" # the base hostname & protocol for your site
github_username:  venam
highlighter: rouge

# Build settings
markdown: kramdown
